apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
namespace : dev-wwwphp
## ajoute le préfixe n'écrase le préfixe précédent
namePrefix: dev-
replicas:
  - name: wwwphp
    count: 3
images:
  - name: php:8.2-fpm
    newTag: 8.3-fpm
configMapGenerator:
  - name: wwwphp-user-env
    behavior: replace
    ## choix de la surcharge !!!
    # literals:
    #   - USER=mike
    envs:
      - files/.env
  
