apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: hello
  name: hello
spec:
  replicas: 3
  # dns local dans les pods
  serviceName: hello-set
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      # conteneurs auxiliaires
      ## 1/ s'exécutent avant les ctns principaux, s'arrêtent avant l'execution de ces derniers
      ## 2/ sont la pour préconfigurer les ctns principaux
      ## 3/ dans le cas du statefulSet, les != noms d'hôtes bien définis 
      ##    permettent de différencier les configurations (ex: pod master / pod worker)
      initContainers:
        - name: inithello
          image: bash
          command:
            - bash
            - -c
            - |
              if [[ $(hostname) =~ -0$ ]]
              then
                echo Primaire > /mnt/status
              else
                echo Secondaire > /mnt/status
              fi
          # point de montage de notre dossier vide partagé
          volumeMounts:
            - name: mnt
              mountPath: /mnt
      # container principal, applicatif
      containers:
        - image: bob2606/hello-http:0.8.11 
          name: hello
          env:
            - name: SERVICE
              value: hello
          # point de montage de notre dossier vide partagé
          volumeMounts:
            - name: mnt
              mountPath: /var/lib/hello-http
      # ajout d'un volume de type dossier vide
      volumes:
        - name: mnt
          emptyDir: