apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace : wwwphp
commonLabels:
  run: wwwphp
resources:
  - wwwphp-deploy.yml
  - wwwphp-svc.yml
  - wwwphp-nginx-cm.yml
  - wwwphp-secret-mdp.yml
  - wwwphp-user-env.yml