apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-resource-constraint
  namespace: resources
spec:
  limits:
  - default:
      cpu: 400m
    defaultRequest:
      cpu: 200m
    # max:
    #   cpu: 400m
    # min:
    #   cpu: 100m
    type: Container
