apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# le namespace spécifié dans K recouvre toutes les ressources k8s
# REM: le namespace doit être préexistant
namespace : wwwphp
# namePrefix: base-
# toutes les ressources k8s ont ce label
commonLabels:
  app: wwwphp
configMapGenerator:
  - name: wwwphp-nginx-cm
    files:
      - files/default.conf
  - name: wwwphp-user-env
    envs:
      - files/.env
secretGenerator:
  - name: wwwphp-secret-mdp
    literals:
      - MY_PASSWORD=roottoor
resources:
  - pv-nfs.yml
  - pvc-nfs.yml
  - wwwphp-deploy.yml
  - wwwphp-svc.yml
  
