apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# le namespace spécifié dans K recouvre toutes les ressources k8s
# REM: le namespace doit être préexistant
namespace : wwwphp
namePrefix: base-
# toutes les ressources k8s ont ce label
commonLabels:
  app: wwwphp
resources:
  - wwwphp-nginx-cm.yml
  - wwwphp-user-env.yml
  - wwwphp-secret-mdp.yml
  - wwwphp-deploy.yml
  - wwwphp-svc.yml
