apiVersion: v1
kind: Service
metadata:
  labels:
    app: wwwphp
  name: wwwphp
spec:
  ports:
    # port: port d'entrée du service
  - port: 80
    protocol: TCP
    # targetPort: port du pod
    targetPort: http
  # config. de l'association entre service <-> déploiement
  selector:
    app: wwwphp
  type: LoadBalancer